Rover zero 2 migration
RoverRobotics/librover pull request #12
Opened 2021-06-18 20:03 UTC by drhieu

Migrate Rover Zero V 2 to Librover .
Rover Zero V2 is now using librover structure as well as the new PID controller.
ComCan and ComSerial is now using Uint8_t instead of Uint32_t for data vector

2021-06-18 20:13 UTC, drhieu reviewed
Reviewed; Need John for PR approval

2021-06-22 19:14 UTC, jbrover requested changes

2021-06-22 19:14 UTC, jbrover commented on src/comm_can.cpp
> +  if (msg.size() == 9) {
alert: magic number.

2021-06-23 18:39 UTC, drhieu commented on src/comm_can.cpp
> +  if (msg.size() == 9) {
updated with current commit

2021-06-23 19:25 UTC, jbrover approved these changes

2021-06-23 19:25 UTC, merged